# Generated by Django 3.1.1 on 2020-12-01 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pacientes', '0001_initial'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('is_glasses', models.BooleanField(default=False)),
                ('distance', models.CharField(blank=True, choices=[('LE', 'Lejos'), ('CE', 'Cerca')], max_length=2, null=True)),
                ('side', models.CharField(blank=True, choices=[('IZ', 'Izquierda'), ('DE', 'Derecha')], max_length=2, null=True)),
                ('frame', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField(default=1)),
                ('total', models.FloatField(null=True)),
                ('status', models.CharField(choices=[('PN', 'Pendiente'), ('PE', 'Pedido'), ('TA', 'Taller'), ('FI', 'Finalizado')], default='PN', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(default='Producto eliminado', on_delete=django.db.models.deletion.SET_DEFAULT, to='Ventas.product')),
                ('client', models.ForeignKey(default='Cliente eliminado', on_delete=django.db.models.deletion.SET_DEFAULT, to='Pacientes.patients')),
                ('seller', models.ForeignKey(default='Vendedor eliminado', on_delete=django.db.models.deletion.SET_DEFAULT, to='Usuarios.usermoduleprofile')),
            ],
        ),
    ]
