# Generated by Django 3.1.1 on 2020-12-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0001_initial'),
        ('Usuarios', '0001_initial'),
        ('Ventas', '0002_auto_20201202_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pacientes.patients'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.usermoduleprofile'),
        ),
    ]
