# Generated by Django 3.1.1 on 2020-05-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tipe',
            field=models.CharField(choices=[('Tarjeta Crédito', 'Tarjeta Crédito'), ('Tarjeta Débito', 'Tarjeta Débito'), ('Billetera Virtual', 'Billetera Virtual'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=20),
        ),
    ]
